import { DecisionMaker } from "@/types/decisionMaker";

export const sampleDecisionMakers: DecisionMaker[] = [
  {
    id: "1",
    companyId: "acme-ai",
    name: "Sarah Johnson",
    title: "CEO",
    department: "Executive",
    priority: "High",
    confidence: 96,
    recommendation: "Executive Sponsor",
    reasons: [
  "CEO of a company with fewer than 20 employees",
  "No internal Talent Acquisition team detected",
  "Engineering hiring is currently active",
  "Executive likely involved in hiring decisions",
],
    linkedin: "https://linkedin.com/in/sarahjohnson",
    email: "sarah@acmeai.com",
  },
  {
    id: "2",
    companyId: "acme-ai",
    name: "Michael Chen",
    title: "VP Engineering",
    department: "Engineering",
    priority: "High",
    confidence: 93,
    recommendation: "Best First Contact",
    linkedin: "https://linkedin.com/in/michaelchen",
    email: "michael@acmeai.com",
  },
  {
    id: "3",
    companyId: "microsoft",
    name: "David Miller",
    title: "Director of Engineering",
    department: "Engineering",
    priority: "High",
    confidence: 94,
    recommendation: "Technical Decision Maker",
  },
  {
    id: "4",
    companyId: "google",
    name: "Lisa Brown",
    title: "Engineering Manager",
    department: "Engineering",
    priority: "Medium",
    confidence: 90,
    recommendation: "Engineering Hiring Manager",
  },
];